version: '3.1'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    stdin_open: true
    tty: true
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/custom_addons
      - ./filestore:/mnt/odoo/filestore
  db:
    image: postgres:16.2
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
volumes:
  odoo-web-data:
  odoo-db-data:
